### ISSUE TITLE
ImportError: cannot import name 'dict_product' from 'tollan.utils'

### ISSUE THREAD

**Issue by javierzaragoza** [toltec-astro/tolteca#4]
When trying to use the most updated version of tolteca, using for example the command "tolteca setup" I have the following error:

Traceback (most recent call last):
  File "/home/apps/tolteca-citlali/anaconda3/envs/tolteca_v02/lib/python3.8/site-packages/tolteca/utils/runtime_context.py", line 1054, in from_dir
    dirconf = DirConf.populate_dir(dirpath, **kwargs)
  File "/home/apps/tolteca-citlali/anaconda3/envs/tolteca_v02/lib/python3.8/site-packages/tolteca/utils/runtime_context.py", line 654, in populate_dir
    from ..simu2 import simu_config_item_types
  File "/home/apps/tolteca-citlali/anaconda3/envs/tolteca_v02/lib/python3.8/site-packages/tolteca/simu2/__init__.py", line 15, in <module>
    from ..utils.common_schema import PhysicalTypeSchema
  File "/home/apps/tolteca-citlali/anaconda3/envs/tolteca_v02/lib/python3.8/site-packages/tolteca/utils/common_schema.py", line 6, in <module>
    from tollan.utils import ensure_abspath, dict_product
ImportError: cannot import name 'dict_product' from 'tollan.utils' (/home/apps/tolteca-citlali/anaconda3/envs/tolteca_v02/lib/python3.8/site-packages/tollan/utils/__init__.py)

The cause is that the line 6 in tolteca/utils/common_schema.py tries to import dict_product from tollan.utils, which is not defined, at least in the current version of tollan. Same error appears when running "tolteca simu" or "tolteca simu2"

**Comment by javierzaragoza** [comment]
dict_product is defined in the develop branch of tollan, so the issue is fixed after installing that branch:

git clone https://github.com/toltec-astro/tollan
cd tollan
git checkout develop
git submodule update --init --recursive
pip install -e .
